server:
  port:8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    username: ENC(D0TwFTGDB9dHlGX/n/fhDQ==)
    password: ENC(1mYYleT4p8iCyvyRYYXD4c8KZMH5o3fH)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/Project_movie_reservation?useUnicode=true&characterEncoding=UTF-8

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jasypt:
  encryptor:
    password: ${JASYPT_SECRET_KEY}
    bean: jasyptStringEncryptor

email:
  address: ENC(C/MpPL0ouJyA/JYMEPQrfHocYQvCMSUAOegj2aqWtc0=)
  app-password: ENC(oerK0LFU32x7l/dB1M4R62Mu6ckN3GHLRlcll5BBb48=)

jwtpassword:
  source: ENC(JAHmuvXaq+u06FFKdeJT41aCVDmgPeTC)

  logging:
    level: debug
