server:
  port:8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    username: ENC(O96lxwPsGQwI759ISeF+lA==)
    password: ENC(2ar45WXl0pWmg5gOMLRR2LmuGTIY+sY1)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/Project_movie_reservation?useUnicode=true&characterEncoding=UTF-8

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jasypt:
  encryptor:
    password: ${JASYPT_SECRET_KEY}
    bean: jasyptStringEncryptor

email:
  address: ENC(676rIggCNA12w8iy1K4r1Q7yp1PqzJ9XGgcrsOl7fdE=)
  app-password: ENC(o6aFRHt8gyml6kZI+FbG/5FTwg0Do7ys) //ilovemovie

jwtpassword:
  source: ENC(gc7Nnx9mEi7UbVtWQ7aPpEY+IGRXiKXq)

  logging:
    level: debug
